spring.rabbitmq.addresses: localhost:5656,localhost:5757,localhost:5858
spring.rabbitmq.username: admin
spring.rabbitmq.password: qBNUPHkRtTs8jKSf
spring.rabbitmq.listener.simple.max-concurrency: 15
spring.rabbitmq.listener.simple.concurrency: 10